### ISSUE TITLE
There are no package on npm

### ISSUE THREAD

**Issue by uetchy** [textlint-ja/textlint-rule-no-dropping-the-ra#1]
I was trying to `npm i -D textlint-rule-no-dropping-the-ra` and it failed with error:

```
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/textlint-rule-no-dropping-the-ra
```

Is this temporary situation or no longer maintained?

**Comment by azu** [comment]
@uetchy Ah-, I forget to publish.
Release textlint-rule-no-dropping-the-ra@1.0.1 Now!

**Comment by uetchy** [comment]
Now it works. Thank you for the quick response!
